name: release
on:
  release:
    types: [published]
    tags:
      - v*

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"
          architecture: x64

      - name: Build sdist and wheel
        run: |
          pip install --upgrade setuptools pip wheel build
          pip install -r requirements.pip
          python3 -m build --no-isolation

      - name: Push release to PyPI
        if: github.event_name == 'release'
        run: |
          pip install --upgrade twine
          twine check dist/*
          twine upload dist/*
